In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
A = np.array(range(1,13)).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
np.random.seed(2)
B = np.random.rand(12).reshape(3,4)
print(B)

[[0.4359949  0.02592623 0.54966248 0.43532239]
 [0.4203678  0.33033482 0.20464863 0.61927097]
 [0.29965467 0.26682728 0.62113383 0.52914209]]


In [6]:
# print( np.dot(A, B)) 
# geht nicht weil Dimensionen falsch

In [7]:
C = np.dot(A,B.T)
print(C)

[[ 3.87812437  4.17206721  4.8132791 ]
 [ 9.66574839 10.47055611 11.6803106 ]
 [15.45337241 16.769045   18.54734211]]


In [8]:
print(C.shape)

(3, 3)


In [9]:
print(C[:,0])

[ 3.87812437  9.66574839 15.45337241]


In [10]:
print(C.diagonal())

[ 3.87812437 10.47055611 18.54734211]


In [11]:
print(np.linalg.inv(C))

[[-3.43077057e+14  6.86154114e+14 -3.43077057e+14]
 [ 2.52418232e+14 -5.04836463e+14  2.52418232e+14]
 [ 5.76300817e+13 -1.15260163e+14  5.76300817e+13]]


In [14]:
np.mean(B)

0.3948571753142061

In [37]:
print((C[]))

SyntaxError: invalid syntax (<ipython-input-37-36bf75f26c9f>, line 1)